apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: authserverx
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/basalami2016/authserverx
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authserverx
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: authserverx
