apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: authserver
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/basalami2016/authserver
  ref:
    branch: master
