metadata:
  name: authserver
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/basalami2016/authserver
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authserver
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: "./application" #
  prune: true
  timeout: 1m
